In [1]:
import numpy as np

In [77]:
m1 = np.array([[2, 3, 6], [1, 3, 4], [2, 8, 7]])
print(m1)

m2 = np.arange(1,10)
m_s2 = m2.reshape(3,3)
print(m_s2)

m3 = np.arange(10,21,2)
m_s3 = m3.reshape(3,2)
print(m_s3)

[[2 3 6]
 [1 3 4]
 [2 8 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 12]
 [14 16]
 [18 20]]


In [78]:
m4 = np.array([[12.3, 34.5, 21.2, 90.0],
               [51.4, 87.2, 77.3, 88.4], 
               [22.2, 41.9, 40.1, 20.0], 
               [91.21, 85.5, 89.2, 21.3], 
               [32, 68, 47, 66]])
print(m4)

[[12.3  34.5  21.2  90.  ]
 [51.4  87.2  77.3  88.4 ]
 [22.2  41.9  40.1  20.  ]
 [91.21 85.5  89.2  21.3 ]
 [32.   68.   47.   66.  ]]


In [79]:
print(sum(m4))

A = m4.transpose()
print(A)

[209.11 317.1  274.8  285.7 ]
[[12.3  51.4  22.2  91.21 32.  ]
 [34.5  87.2  41.9  85.5  68.  ]
 [21.2  77.3  40.1  89.2  47.  ]
 [90.   88.4  20.   21.3  66.  ]]


In [80]:
A1 = np.arange(61,106).reshape(5,9)
print(A1)
A2 = np.arange(50,79,2).reshape(3,5)
print(A2)

[[ 61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78]
 [ 79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96]
 [ 97  98  99 100 101 102 103 104 105]]
[[50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]]


In [83]:
M1 = m_s2 * m1
print(M1)

[[ 2  6 18]
 [ 4 15 24]
 [14 64 63]]


In [85]:
#Matrix Multiplication Using Dots()
M2 = m_s2.dot(m1)
print(M2)

[[ 10  33  35]
 [ 25  75  86]
 [ 40 117 137]]
